lora_config:
  r: 16
  lora_alpha: 32
  lora_dropout: 0.5
  bias: "none"
  task_type: "CAUSAL_LM"

dataset:
  name: "NTTUNLPTEAM/class-text"
  split: "train"

model:
  name: "mistralai/Mistral-7B-v0.1"

training_args:
  output_dir: "output"
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 4
  learning_rate: 5e-5
  logging_steps: 100

trainer:
  dataset_text_field: "text"
  max_seq_length: 512