lora_config:
  r: 16
  lora_alpha: 32
  lora_dropout: 0.5
  bias: "none"
  task_type: "CAUSAL_LM"

dataset:
  name: "NTTUNLPTEAM/class-textbook"
  split: "train"

model:
  name: "openai-community/gpt2"

api_tokens:
  huggingface: "YOUR_HUGGINGFACE_API_TOKEN"

training_args:
  output_dir: "Test-model"
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 4
  learning_rate: 0.00005
  logging_steps: 100
  push_to_hub: True
  push_to_organization: False

trainer:
  dataset_text_field: "text"
  max_seq_length: 512

fine_tuning:
  method: "lora" # "lora" or "full"